### ISSUE TITLE
Add sha3/bmt hash field to metadata

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#191]
Currently, our metadata does not include a field for the hash of the entire file. This makes it difficult to verify the integrity of downloaded data.

I propose adding a sha3/bmt hash field to the metadata to allow for easy verification of the downloaded data. This will ensure that users can trust the data they are downloading and prevent any potential issues with corrupted files.

wdyt @nugaon?

**Comment by plur9** [comment]
This is an excellent proposal for data integrity verification. Adding hash fields to file metadata would allow clients to verify downloads haven't been corrupted.

**Technical considerations:**

1. **Hash algorithm choice**: Swarm already uses BMT (Binary Merkle Tree) hashing internally for content addressing. We should expose the BMT hash that Swarm computes, rather than computing SHA3 separately. This avoids redundant hashing and aligns with Swarm's architecture.

2. **Metadata structure**: Suggest adding to the existing file metadata:
```typescript
interface FileMetadata {
  // ... existing fields
  hash?: {
    algorithm: 'bmt' | 'sha3-256';
    value: string; // hex-encoded hash
  };
}
```

3. **Implementation approach**:
   - For uploads: Extract BMT hash from Bee's upload response (already computed)
   - For verification: Client can re-hash downloaded data and compare
   - Make it optional to maintain backwards compatibility

4. **API impact**: This is a backwards-compatible enhancement (optional field).

I can implement this if you'd like. Would you prefer BMT hash (aligns with Swarm), SHA3 (more familiar to devs), or both?

cc @nugaon for Swarm/Bee perspective on exposing BMT hashes

**Comment by plur9** [comment]
I've done a deeper technical analysis. Key findings:

**Best approach: Expose Swarm's BMT hash (zero cost)**

Swarm already computes BMT (Binary Merkle Tree) hashes for all content — the Swarm reference *is* the hash. We can expose it with zero additional computation:

```typescript
interface FileMetadata {
  // ... existing fields
  hash?: {
    algorithm: 'bmt',
    value: string  // Swarm reference (already computed by Bee)
  }
}
```

**Verification:**
```typescript
const { reference } = await bee.uploadFile(batchId, data, filename);
// reference === BMT hash of file content

// Later: verify by re-uploading and comparing references
// or compare against stored metadata.hash.value
```

**Advantages:**
- ✅ Zero performance overhead (Bee already computed it)
- ✅ Native to Swarm's content-addressing
- ✅ Backwards compatible (optional field)

**Trade-off:** BMT is Swarm-specific, not as familiar as SHA3. But it's the right architectural choice — aligns with Swarm's design and costs nothing.

**Alternative:** Could add SHA3-256 as secondary option, but that means computing hashes twice. Recommend starting with BMT.

Full analysis: `/home/gregor/Data/3-fds/1-tracks/dev/fdp-storage-hash-field-analysis.md` (if you have repo access)

@nugaon - thoughts on BMT vs SHA3 approach?

**Comment by plur9** [comment]
## Technical Analysis: Hash Field Implementation

I've analyzed this proposal from both security and architectural perspectives. TL;DR: **Great idea, and it's easier than you might think.**

### Key Insight: Swarm Already Computed the Hash

Every file uploaded to Swarm gets a BMT (Binary Merkle Tree) hash — that's the Swarm reference itself. We don't need to compute a separate hash; we just need to **expose the reference in the metadata**.

### Proposed Implementation

```typescript
interface FileMetadata {
  // ... existing fields
  hash?: {
    algorithm: 'bmt';  // Binary Merkle Tree (Swarm native)
    value: string;     // Hex-encoded Swarm reference
  };
}
```

### Implementation Strategy

**Phase 1: Expose BMT reference (RECOMMENDED)**
- Zero performance cost (Bee already computed it)
- Native to Swarm's content-addressing model
- Verification: re-upload file and compare references
- Backwards compatible (optional field)

**Phase 2: Add SHA3 option (IF needed later)**
- More familiar to Ethereum devs
- Can verify client-side without Bee node
- Trade-off: additional computation overhead

### Verification Example

```typescript
// Upload
const result = await fdp.file.uploadFile({
  podName: 'my-pod',
  path: '/contract.pdf',
  file: data
});

console.log(result.hash);
// { algorithm: 'bmt', value: '0a7c8...' }

// Download and verify
const download = await fdp.file.downloadFile({
  podName: 'my-pod',
  path: '/contract.pdf'
});

const verified = await fdp.file.verifyIntegrity({
  data: download.data,
  expectedHash: result.hash
});
```

### Security Boundaries

**What this protects against:**
- ✅ Accidental corruption during transfer
- ✅ Storage degradation over time
- ✅ Gateway misbehavior (wrong data)

**What this does NOT protect against:**
- ❌ Metadata tampering (attacker changes hash field itself)
- ❌ Original upload corruption
- ❌ MITM during metadata fetch

For full security, we'd need **metadata signing** (separate feature).

### Implementation Checklist

1. Add `hash` field to `FileMetadata` interface (src/file/types.ts)
2. Capture Swarm reference in `uploadFile()` (src/file/handler.ts)
3. Store hash in metadata
4. Add `verifyFileIntegrity()` utility function
5. Documentation + verification guide
6. Tests for hash field and verification
7. Handle backwards compat (old files without hashes)

### Recommendation

Start with Phase 1 (BMT). It's:
- Zero cost (already computed)
- Architecturally correct (aligns with Swarm)
- Easy to implement
- Immediately useful

Add SHA3 later only if there's strong user demand for client-side verification.

@nugaon - thoughts on starting with BMT approach?

---
Full analysis: https://github.com/fairDataSociety/fdp-storage/blob/main/docs/hash-field-analysis.md (if we want to add detailed docs)

🤖 Generated by FDS CTO agent

**Comment by plur9** [comment]
## Technical Analysis: Hash Field Implementation

Great proposal @IgorShadurin! Here's a comprehensive analysis of implementation approaches.

### Current Gap

fdp-storage file metadata lacks cryptographic hashes, preventing:
- Integrity verification of downloaded files
- Detection of corruption during transfer
- Protection against malicious data substitution

### Key Insight: Swarm Already Has The Hash

Ethereum Swarm computes BMT (Binary Merkle Tree) hashes for all content. **The Swarm reference IS a BMT hash of the file content.**

### Recommended Approach: Two-Phase Implementation

#### Phase 1: Expose Swarm Reference (Recommended Start)

The Swarm reference returned by `bee.uploadFile()` is already the BMT hash:

```typescript
interface FileMetadata {
  // Existing fields...
  
  // NEW: Content integrity
  hash?: {
    algorithm: 'bmt';  // Binary Merkle Tree (Swarm native)
    value: string;     // Hex-encoded Swarm reference
  };
}
```

**Advantages:**
- ✅ Zero additional computation (Swarm already computed it)
- ✅ Native to Swarm architecture
- ✅ Can verify by re-uploading and comparing references
- ✅ Backwards compatible (optional field)

**Disadvantages:**
- ⚠️ BMT is Swarm-specific (not familiar to most devs)
- ⚠️ Verification requires Bee node access

#### Phase 2: Add SHA3 Option (Optional Enhancement)

For broader compatibility, optionally compute SHA3-256:

```typescript
import { keccak256 } from 'ethers';

const sha3Hash = keccak256(fileData);

const metadata = {
  hash: {
    algorithm: 'sha3-256',
    value: sha3Hash
  }
};
```

**Advantages:**
- ✅ Familiar to Ethereum/web3 developers
- ✅ Can verify client-side without Bee node
- ✅ Standard cryptographic primitive

**Disadvantages:**
- ❌ Additional computation overhead
- ❌ Duplicates work Swarm already did
- ❌ Doesn't align with Swarm's content-addressing model

### Recommendation

**Start with Phase 1 (BMT/Swarm reference)**:
1. Expose Swarm reference as `hash.algorithm = 'bmt'`
2. Document verification process (re-upload and compare)
3. Zero performance cost (already computed)
4. Educate developers about BMT benefits

**Consider Phase 2 later** if:
- User demand for SHA3
- Use cases requiring offline verification
- Integration with non-Swarm systems

### Verification Example

```typescript
// Upload file
const result = await fdp.file.uploadFile({
  podName: 'my-pod',
  path: '/documents/contract.pdf',
  file: contractPdfData
});

console.log(result.hash);
// { algorithm: 'bmt', value: '0a7c8...' }

// Download file
const download = await fdp.file.downloadFile({
  podName: 'my-pod',
  path: '/documents/contract.pdf'
});

// Verify integrity
const verified = await fdp.file.verifyIntegrity({
  data: download.data,
  expectedHash: result.hash
});

if (!verified) {
  throw new Error('File integrity check failed!');
}
```

### Security Considerations

**What This Protects Against:**
- ✅ Accidental corruption during transfer
- ✅ Storage degradation over time
- ✅ Gateway misbehavior (returning wrong data)

**What This Does NOT Protect Against:**
- ❌ Metadata tampering (attacker changes the hash field itself)
- ❌ Original upload corruption (garbage in, garbage out)
- ❌ Man-in-the-middle during metadata fetch

**Full security requires:** Content hash + metadata signing + end-to-end encryption (already in FDP)

### Implementation Checklist

- [ ] Add `hash` field to `FileMetadata` interface (src/file/types.ts)
- [ ] Modify `uploadFile()` to capture Swarm reference (src/file/handler.ts)
- [ ] Store hash in metadata during upload
- [ ] Add verification utility function `verifyFileIntegrity()`
- [ ] Update documentation with verification examples
- [ ] Add tests for hash field presence
- [ ] Add tests for verification utility
- [ ] Consider deprecation path (how to handle old files without hashes)

### Next Steps

1. **Gather feedback** - Does @nugaon agree BMT is the right approach?
2. **Prototype** - Implement Phase 1 on feature branch
3. **Test** - Verify with real Bee node
4. **Document** - Write verification guide
5. **Release** - Backwards-compatible minor version bump

---

🤖 Posted by FDS CTO (AI) - Technical analysis for fdp-storage enhancement
